spring.application.name=TiliRegister
spring.datasource.url=jdbc:mysql://localhost:3306/tili_register?useSSL=false&serverTimezone=UTC
spring.datasource.username=junior
spring.datasource.password=P@55w0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

#spring.mail.host=${TILI_MAIL_HOST}
#spring.mail.port=587
#spring.mail.username=${TILI_MAIL_USERNAME}
#spring.mail.password=${TILI_MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

server.address=0.0.0.0
server.port=8080

jwt.secret=${TILI_JWT_SECRET}

tili.api.baseurl=${TILI_API_BASE_URL}
tili.reset-password.base-url=${TILI_RESET_PASSWORD_BASE_URL}
